language: android
android:
  components:
    - build-tools-21.1.1
    - android-21

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

script:
  ./gradlew build
